import type { Config } from 'tailwindcss';

/**
 * NECKLINE - Tailwind theme
 * Every value resolves through CSS variables defined in src/styles/tokens.css.
 * The CSS file is the single source of truth - DO NOT hardcode values here.
 */
const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-pressed': 'var(--color-primary-pressed)',
        'primary-glow': 'var(--color-primary-glow)',
        gold: 'var(--color-gold)',
        success: 'var(--color-success)',
        'success-hover': 'var(--color-success-hover)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
        error: 'var(--color-error)',
        live: 'var(--color-live)',
        'live-fg': 'var(--color-live-fg)',
        notification: 'var(--color-notification)',
        bg: 'var(--color-bg)',
        'bg-translucent': 'var(--color-bg-translucent)',
        'bg-deep': 'var(--color-bg-deep)',
        'bg-secondary': 'var(--color-bg-secondary)',
        surface: 'var(--color-surface)',
        'surface-alt': 'var(--color-surface-alt)',
        'surface-elevated': 'var(--color-surface-elevated)',
        'surface-input': 'var(--color-surface-input)',
        'surface-overlay': 'var(--color-surface-overlay)',
        'admin-bg': 'var(--color-admin-bg)',
        'admin-surface': 'var(--color-admin-surface)',
        'admin-surface-elevated': 'var(--color-admin-surface-elevated)',
        'admin-border': 'var(--color-admin-border)',
        'admin-border-subtle': 'var(--color-admin-border-subtle)',
        'admin-border-strong': 'var(--color-admin-border-strong)',
        'login-overlay': 'var(--color-login-overlay)',
        'login-card': 'var(--color-login-card)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        'border-card-hover': 'var(--color-border-card-hover)',
        'border-input-focus': 'var(--color-border-input-focus)',
        divider: 'var(--color-divider)',
        'text-primary': 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-secondary-alt': 'var(--color-text-secondary-alt)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-muted': 'var(--color-text-muted)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-brand': 'var(--color-text-brand)',
        'text-live': 'var(--color-text-live)',
        'text-warning': 'var(--color-text-warning)',
        'success-fg': 'var(--color-success-fg)',
        'success-bg': 'var(--color-success-bg)',
        'error-fg': 'var(--color-error-fg)',
        'error-bg': 'var(--color-error-bg)',
        'error-border': 'var(--color-error-border)',
        'warning-fg': 'var(--color-warning-fg)',
        'warning-bg': 'var(--color-warning-bg)',
        'info-fg': 'var(--color-info-fg)',
        'info-bg': 'var(--color-info-bg)',
        'brand-alert-fg': 'var(--color-brand-alert-fg)',
        'brand-alert-bg': 'var(--color-brand-alert-bg)',
        'brand-alert-border': 'var(--color-brand-alert-border)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'chart-4': 'var(--chart-4)',
        'chart-5': 'var(--chart-5)',
        'chart-6': 'var(--chart-6)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-serif)', 'Georgia', 'serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        xs: 'var(--fs-xs)',
        sm: 'var(--fs-sm)',
        base: 'var(--fs-base)',
        lg: 'var(--fs-lg)',
        xl: 'var(--fs-xl)',
        '2xl': 'var(--fs-2xl)',
        '3xl': 'var(--fs-3xl)',
        '4xl': 'var(--fs-4xl)',
        '5xl': 'var(--fs-5xl)',
        '6xl': 'var(--fs-6xl)',
      },
      fontWeight: {
        regular: 'var(--fw-regular)',
        medium: 'var(--fw-medium)',
        semibold: 'var(--fw-semibold)',
        bold: 'var(--fw-bold)',
        black: 'var(--fw-black)',
      },
      lineHeight: {
        tight: 'var(--lh-tight)',
        snug: 'var(--lh-snug)',
        normal: 'var(--lh-normal)',
        relaxed: 'var(--lh-relaxed)',
      },
      letterSpacing: {
        tight: 'var(--ls-tight)',
        normal: 'var(--ls-normal)',
        wide: 'var(--ls-wide)',
        wider: 'var(--ls-wider)',
        widest: 'var(--ls-widest)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        focus: 'var(--shadow-focus)',
        glow: 'var(--shadow-glow)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        DEFAULT: 'var(--duration-base)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        standard: 'var(--ease-standard)',
        out: 'var(--ease-out)',
      },
      zIndex: {
        base: 'var(--z-base)',
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        overlay: 'var(--z-overlay)',
        modal: 'var(--z-modal)',
        toast: 'var(--z-toast)',
      },
      maxWidth: { container: 'var(--container-max)' },
      width: { sidebar: 'var(--sidebar-width)' },
    },
  },
  plugins: [],
};

export default config;
