import type { Config } from 'tailwindcss';

/**
 * NECKLINE - Tailwind theme v2.0
 * Every value resolves through CSS variables defined in src/styles/tokens.css.
 * The CSS file is the single source of truth - DO NOT hardcode values here.
 */
const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // v2.0 core palette
        noir: 'var(--noir)',
        'noir-lift': 'var(--noir-lift)',
        'noir-deep': 'var(--noir-deep)',
        crimson: 'var(--crimson)',
        'crimson-light': 'var(--crimson-light)',
        'crimson-dark': 'var(--crimson-dark)',
        'crimson-glow': 'var(--crimson-glow)',
        'warm-white': 'var(--warm-white)',
        muted: 'var(--muted)',
        'muted-deep': 'var(--muted-deep)',
        success: 'var(--success)',
        error: 'var(--error)',
        'oud-amber': 'var(--oud-amber)',
        'rose-blush': 'var(--rose-blush)',
        'musk-silver': 'var(--musk-silver)',
        'original-gold': 'var(--original-gold)',
        'glass-surface': 'var(--glass-surface)',
        'glass-border': 'var(--glass-border)',
        'glass-highlight': 'var(--glass-highlight)',
        'glass-strong': 'var(--glass-strong)',
        'glass-input': 'var(--glass-input)',

        // Legacy aliases (preserved during migration)
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-pressed': 'var(--color-primary-pressed)',
        'primary-glow': 'var(--color-primary-glow)',
        gold: 'var(--color-gold)',
        'success-hover': 'var(--color-success-hover)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
        live: 'var(--color-live)',
        'live-fg': 'var(--color-live-fg)',
        notification: 'var(--color-notification)',
        bg: 'var(--color-bg)',
        'bg-translucent': 'var(--color-bg-translucent)',
        'bg-deep': 'var(--color-bg-deep)',
        'bg-secondary': 'var(--color-bg-secondary)',
        surface: 'var(--color-surface)',
        'surface-alt': 'var(--color-surface-alt)',
        'surface-elevated': 'var(--color-surface-elevated)',
        'surface-input': 'var(--color-surface-input)',
        'surface-overlay': 'var(--color-surface-overlay)',
        'admin-bg': 'var(--color-admin-bg)',
        'admin-surface': 'var(--color-admin-surface)',
        'admin-surface-elevated': 'var(--color-admin-surface-elevated)',
        'admin-border': 'var(--color-admin-border)',
        'admin-border-subtle': 'var(--color-admin-border-subtle)',
        'admin-border-strong': 'var(--color-admin-border-strong)',
        'login-overlay': 'var(--color-login-overlay)',
        'login-card': 'var(--color-login-card)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
        'border-card-hover': 'var(--color-border-card-hover)',
        'border-input-focus': 'var(--color-border-input-focus)',
        divider: 'var(--color-divider)',
        'text-primary': 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-secondary-alt': 'var(--color-text-secondary-alt)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-muted': 'var(--color-text-muted)',
        'text-disabled': 'var(--color-text-disabled)',
        'text-inverse': 'var(--color-text-inverse)',
        'text-brand': 'var(--color-text-brand)',
        'text-live': 'var(--color-text-live)',
        'text-warning': 'var(--color-text-warning)',
        'success-fg': 'var(--color-success-fg)',
        'success-bg': 'var(--color-success-bg)',
        'error-fg': 'var(--color-error-fg)',
        'error-bg': 'var(--color-error-bg)',
        'error-border': 'var(--color-error-border)',
        'warning-fg': 'var(--color-warning-fg)',
        'warning-bg': 'var(--color-warning-bg)',
        'info-fg': 'var(--color-info-fg)',
        'info-bg': 'var(--color-info-bg)',
        'brand-alert-fg': 'var(--color-brand-alert-fg)',
        'brand-alert-bg': 'var(--color-brand-alert-bg)',
        'brand-alert-border': 'var(--color-brand-alert-border)',
        'chart-1': 'var(--chart-1)',
        'chart-2': 'var(--chart-2)',
        'chart-3': 'var(--chart-3)',
        'chart-4': 'var(--chart-4)',
        'chart-5': 'var(--chart-5)',
        'chart-6': 'var(--chart-6)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'system-ui', 'sans-serif'],
        body: ['var(--font-body)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-serif)', 'Georgia', 'serif'],
      },
      fontSize: {
        display: 'var(--text-display)',
        headline: 'var(--text-headline)',
        'headline-sm': 'var(--text-headline-sm)',
        overline: 'var(--text-overline)',
        body: 'var(--text-body)',
        'body-sm': 'var(--text-body-sm)',
        label: 'var(--text-label)',
        button: 'var(--text-button)',
        mono: 'var(--text-mono)',
        price: 'var(--text-price)',
        xs: 'var(--fs-xs)',
        sm: 'var(--fs-sm)',
        base: 'var(--fs-base)',
        lg: 'var(--fs-lg)',
        xl: 'var(--fs-xl)',
        '2xl': 'var(--fs-2xl)',
        '3xl': 'var(--fs-3xl)',
        '4xl': 'var(--fs-4xl)',
        '5xl': 'var(--fs-5xl)',
        '6xl': 'var(--fs-6xl)',
      },
      fontWeight: {
        regular: 'var(--fw-regular)',
        medium: 'var(--fw-medium)',
        semibold: 'var(--fw-semibold)',
        bold: 'var(--fw-bold)',
        black: 'var(--fw-black)',
      },
      lineHeight: {
        display: 'var(--leading-display)',
        headline: 'var(--leading-headline)',
        'headline-sm': 'var(--leading-headline-sm)',
        body: 'var(--leading-body)',
        'body-sm': 'var(--leading-body-sm)',
        tight: 'var(--leading-tight)',
        snug: 'var(--lh-snug)',
        normal: 'var(--lh-normal)',
        relaxed: 'var(--lh-relaxed)',
      },
      letterSpacing: {
        display: 'var(--tracking-display)',
        headline: 'var(--tracking-headline)',
        'headline-sm': 'var(--tracking-headline-sm)',
        overline: 'var(--tracking-overline)',
        label: 'var(--tracking-label)',
        button: 'var(--tracking-button)',
        mono: 'var(--tracking-mono)',
        body: 'var(--tracking-body)',
        tight: 'var(--ls-tight)',
        normal: 'var(--ls-normal)',
        wide: 'var(--ls-wide)',
        wider: 'var(--ls-wider)',
        widest: 'var(--ls-widest)',
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
        '32': 'var(--space-32)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
        modal: 'var(--shadow-modal)',
        glass: 'var(--shadow-glass)',
        'aura-oud': 'var(--shadow-aura-oud)',
        'aura-rose': 'var(--shadow-aura-rose)',
        'aura-musk': 'var(--shadow-aura-musk)',
        'aura-original': 'var(--shadow-aura-original)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        focus: 'var(--shadow-focus)',
        glow: 'var(--shadow-glow)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        medium: 'var(--duration-medium)',
        slow: 'var(--duration-slow)',
        dramatic: 'var(--duration-dramatic)',
        DEFAULT: 'var(--duration-base)',
        base: 'var(--duration-base)',
      },
      transitionTimingFunction: {
        'out-expo': 'var(--ease-out-expo)',
        'out-back': 'var(--ease-out-back)',
        'in-out-smooth': 'var(--ease-in-out-smooth)',
        standard: 'var(--ease-standard)',
        out: 'var(--ease-out)',
      },
      zIndex: {
        base: 'var(--z-base)',
        elevated: 'var(--z-elevated)',
        sticky: 'var(--z-sticky)',
        nav: 'var(--z-nav)',
        drawer: 'var(--z-drawer)',
        modal: 'var(--z-modal)',
        overlay: 'var(--z-overlay)',
        noise: 'var(--z-noise)',
        dropdown: 'var(--z-dropdown)',
        toast: 'var(--z-toast)',
      },
      maxWidth: { container: 'var(--container-max)', content: 'var(--content-max)' },
      width: { sidebar: 'var(--sidebar-width)' },
    },
  },
  plugins: [],
};

export default config;
